# Note that this Docker configuration is exclusively for starting up the server on a local machine so that experiments can be run by researchers even without any internet connection. The production web app is NOT deployed via Docker for now.
---
version: '3.9'
services:
  web:
    # The path that contains Dockerfile
    build: .
    # Map the 4000 of localhost to the 4000 of the container
    ports:
      - 4000:4000
    environment:
      - MAGPIE_DB_HOST=db
      - MIX_ENV=dev
      - PORT=4000
    # Ensures that the postgres service is started first.
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: magpie_dev
